apiVersion: v1
kind: Service
metadata:
  name: croyale-redis-service
spec:
  selector:
    app: croyale
    tier: redis
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379